### ISSUE TITLE
Integrate with `EXPORT AWS_PROFILE=...` way of setting profiles

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#102]
**Is your feature request related to a problem? Please describe.**
We recently introduced a feature to pick an AWS profile that Collie will use for doing CLI calls. But @SimonTheLeg made a good remark where he explained that some AWS devs will be used to doing so using the `EXPORT AWS_PROFILE=...` method.

**Reach of the feature request**
AWS developers using `EXPORT AWS_PROFILE` for picking profiles

**Impact of the feature request**
They might be confused about what exact profile is used. Especially if they first run `EXPORT AWS_PROFILE` and then `collie tenant list` where Collie might use a different profile.

**How would a solution look like?**
At best, Collie would have to detect `EXPORT AWS_PROFILE`, and use that profile instead of the one configured using `collie config aws`.

**Comment by tfelix** [comment]
We already just "use" the regular mechanics for AWS Cli authentication. So if we detect the presence of this ENV var we should just ignore our manual profile selection.

**Comment by tfelix** [comment]
I checked how AWS cli works and it might be that our flag provided will overwrite the existing ENV variable (or at least it will get ignored).
