### ISSUE TITLE
collie upgrade

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/collie-cli#108]
**Is your feature request related to a problem? Please describe.**
Collie ships new updates regularly, this is cool :-) But I have to "work" to get them. 

Can you support a `collie upgrade` command like `deno upgrade`?

**Reach of the feature request**
me

**Impact of the feature request**
Saves me time, I can use more awesome collie stuff 

**How would a solution look like?**
see below

(optional) **Implementation Hints**
 Cliffy seems to have that builtin 😍  https://cliffy.io/command/index.html#%E2%9D%AF-upgrade-command

**Comment by tfelix** [comment]
Thanks for the idea.
If I am not mistaken, Cliffy Upgrade only checks out a GitHub branch/source and then invokes the Deno interpreter. As we however perform a compilation and binary download, this won't work. 
We probably need some kind of loader which fetches the binary file and also elevates to root access as we write in protected paths to setup the binary in the PATH (`/usr/local/bin`).

**Comment by Jelledb** [comment]
> Thanks for the idea.
> If I am not mistaken, Cliffy Upgrade only checks out a GitHub branch/source and then invokes the Deno interpreter. As we however perform a compilation and binary download, this won't work.
> We probably need some kind of loader which fetches the binary file and also elevates to root access as we write in protected paths to setup the binary in the PATH (`/usr/local/bin`).

I also guess a good first start is just logging "Dear user, a new Collie version is available. Head to <github link> to do an upgrade".
