### ISSUE TITLE
Deprovision Tenants with Collie

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#109]
**Is your feature request related to a problem? Please describe.**
I would love to deprovision tenants using Collie as this is a huge pain in the ass by doing it manually in the UI. In my example, this problem goes for AWS, but it might be just as painful for the other platforms as well.

**Reach of the feature request**
Platform Operators and Project Owners responsible for deleting accounts

**Impact of the feature request**
Deleting faster could result in a better user experience and even in potential cost savings by deprovisioning unused resources ASAP.

**How would a solution look like?**
`collie tenant delete <identifier>`
Not sure how the identifier part would work exactly though. Especially if you have duplicate identifiers across multiple platforms.

(optional) **Implementation Hints**
Check if the cloud CLIs allow for deletion. It might be that this is not possible.

**Comment by Jelledb** [comment]
Before we go on with defining a solution, the first step would be to estimate if this is doable for which cloud platforms. I know from experience that e.g. AWS requires a credit card and makes this quite difficult.

**Comment by JohannesRudolph** [comment]
Closed due to lack of community interest - feel free to revive discussion at https://github.com/meshcloud/collie-cli/discussions
