### ISSUE TITLE
Analyze tag values

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#12]
We are currently capable of analyzing tags on a global level, but it would also be nice to analyze the underlying tag values of one single tag. Take the `environment` tag for example; I would like to know what values are used and by what percentage. This would allow me to identify inconsistencies and see what % of cloud tenants are using a particular environment. The command could work like

`collie analyze-tag-values --tag environment`
->
```
Analyzed 92 tenants
The environment tag has the following values:
-- production (12%)
-- test (20%)
-- development (64%)
-- dev (4%) <-- found inconsistency
```

**Comment by JohannesRudolph** [comment]
Closed due to lack of community interest - feel free to revive discussion at https://github.com/meshcloud/collie-cli/discussions
