### ISSUE TITLE
Leverage JSON schema as the source of truth for the structure of your tags

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#123]
- Analyze incompliances, e.g. env = [dev, qa, prod] but a tag is used with `development`.
- Go into a mode where you can set tags using the JSON schema, e.g. single-select could use the Cliffy selector (suggestions thingy) to select the right values.

**Comment by JohannesRudolph** [comment]
Closed due to lack of community interest - feel free to revive discussion at https://github.com/meshcloud/collie-cli/discussions
