### ISSUE TITLE
Collie shows wrong version number

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#133]
**Describe the bug**
I installed version 0.9.1 but `collie --version` tells me I am on `0.7.0`.

**Reach of the bug**
All users

**Impact of the bug**
False impression that I am behind on versions

**To Reproduce**
- Remove Collie from your system.
- Install Collie as described in the README
- Run `collie --version` and you will see the version number is wrong

(optional) **Implementation Hints**
Is there something wrong with our build? The commit tagged with `0.9.1` contains the correct version number in `version.ts`.

**Comment by JohannesRudolph** [comment]
While looking into this I noticed the following. [235b3f48efcaae449651462ac0c004c875c7f8c4
](https://github.com/meshcloud/collie-cli/commit/235b3f48efcaae449651462ac0c004c875c7f8c4) aimed to fix the release workflow. However from the way the v0.9.1 appears in git history it seems that the tag is still left on a dangling commit
![image](https://user-images.githubusercontent.com/130103/150213676-f6841bd8-b690-4963-bccc-0e424ade91a1.png)
