### ISSUE TITLE
Collie foundation new complains about non-existing collie repo

### ISSUE THREAD

**Issue by sttomm** [meshcloud/collie-cli#165]
**Describe the bug**
I installed the latest collie version, did a `collie init` and wanted to create a foundation. I got:

```
user@MBP-2 collie % collie foundation new my-foundation
Error: /Users/user/dev/collie nor any of its parent directories seemse to be a collie repository
    at Function.load (file:///home/runner/work/collie-cli/collie-cli/src/model/CollieRepository.ts:40:23)
    at async Command.fn (file:///home/runner/work/collie-cli/collie-cli/src/commands/foundation/new.command.ts:14:22)
    at async Command.execute (https://deno.land/x/cliffy@v0.22.2/command/command.ts:577:13)
    at async Command.parse (https://deno.land/x/cliffy@v0.22.2/command/command.ts:509:24)
    at async collie (file:///home/runner/work/collie-cli/collie-cli/src/main.ts:47:9)
Tip: run collie with --verbose and --debug flags for more details
user@MBP-2 collie % ls -lart
total 16
drwxr-xr-x  23 user  staff   736 25 Jul 17:14 ..
-rw-r--r--   1 user  staff  2226 25 Jul 17:15 README.md
-rw-r--r--   1 user  staff   134 25 Jul 17:15 .gitignore
drwxr-xr-x   3 user  staff    96 25 Jul 17:15 kit
drwxr-xr-x   3 user  staff    96 25 Jul 17:15 compliance
drwxr-xr-x   7 user  staff   224 25 Jul 17:15 .
drwxr-xr-x   3 user  staff    96 25 Jul 17:15 foundations
```

**Reach of the bug**
Users wanting to create a new Cloud Foundation via collie. Perhaps only Mac users are affected?

**Impact of the bug**
I can't create a new foundation

**To Reproduce**
1. Install collie.
2. Run `collie init`.
3. Run `collie foundation new my-foundation`
4. The error mentioned above is shown.

**Expected behavior**
I can create a new foundation without an error.

**Screenshots**
added output of commands above

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Version: 12.4
- Collie version 0.11.0

**Comment by malhussan** [comment]
I use Linux and can confirm this error also appears.
