### ISSUE TITLE
Couldn't be able to run collie foundation deploy due to an error in files hierarchy

### ISSUE THREAD

**Issue by ishabakeh** [meshcloud/collie-cli#166]
## "Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a platform.hcl in any of the parent folders"

**Describe the bug**
I made my first kit as the step by step guid, but for deploying it I ran into some issues which says it couldn't find the module.hcl and platform.hcl files in the parent folders (you can find them under foundation/<myfoundation>/platform/<my platform>)

**Reach of the bug**
All the first-timers are impacted

**Impact of the bug**
It prevents to actually deploy my modules into my target platform

**To Reproduce**
1- git init my-foundation-kit
2- cd my-foundation-kit
3- collie init
4- collie foundation new my-foundation-dev
5- collie kit new "my-first-azure-module"
6- collie kit apply "my-first-azure-module" 
7- collie foundation deploy my-foundation-dev

**Expected behavior**
It should make a sub-folder with the name of my kit "my-first-azure-module" under the "platform/<my platform name>" then create the terragrunt.hcl file into this new folder. The tree should be look like this:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/96071919/189302168-09bd5bc1-766e-4979-a3ea-48f3ee4ea740.png">

and the output of "collie kit tree" command:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/96071919/189302359-66fb6bd7-92a8-452b-b7cc-7e6b811ee89f.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 
 - Version 12.5.1
 - Apple M1 chip

**Comment by JohannesRudolph** [comment]
this is possibly out of date, as we noticed no more such issues with the most recent [getting started guide](https://collie.cloudfoundation.org/tutorial/#verify-collie-installation) and there were quite a few changes to collie in between.
