### ISSUE TITLE
Support GCP cost collection

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#17]
GCP cost collection is currently not supported as their CLI does not offer any cost export via `gcloud` CLI. This issue will be used to track progress on this and/or figure out any other methods of retrieving GCP costs.

**Comment by Jelledb** [comment]
I've looked into the possibilities of collecting cost data from GCP for Collie. It seems quite doable, but there is one limitation that cannot be worked around: cost data will only be collected from the moment you active the billing export in GCP. I do expect that some users have this thing enabled already, which means they have some "seed data" to work with, but it might very well be possible that someone did not and it will take some time to accumulate cost data for these users. Neverthless I think it's something we should do to achieve feature parity.

I expect the (roughly) following flow from the user experience:
* Upon initially connecting GCP the user is asked to create a billing export. We can link this guide here directly from Google:  https://cloud.google.com/billing/docs/how-to/export-data-bigquery
* Once completed, we ask the user in which project this billing export is present. We need this info so we know where the billing data lives. We should use the project identifier for this.
* Once the user gave us the project, we can try to detect in which table it is located. To do so, we can do the following
  * (We will use the `bq` CLI which should be included within `gcloud`)
  * Run `bq ls --project_id <project_id> --format json billing_export` to get a list of all datasets. Using the Cliffy prompt we can ask which of these datasets is the one that contains the billing export (if it's just one, we can either auto-confirm of some sort) (make sure to filter for the type = `TABLE`)
  * A dataset can contain multiple tables, so we need to do the same thing within the dataset: `bq ls --project_id <project_id> --format json <billing export dataset name>
* When we know the name of the table, we can create a materialized view. A materialized view can help us vastly reduce the costs of BigQuery as it will precompute the query we will use. The following query will be required:
```
bq --project_id <project_id> query --nouse_legacy_sql \
CREATE MATERIALIZED VIEW `meshstack-root.billing_export.collie-billing-view` AS
SELECT
  invoice.month as `invoice_month`,
  project.id `project_id`,
  (SUM(CAST(cost * 1000000 AS int64) / 1000000)) as `cost`
FROM `meshstack-root.billing_export.gcp_billing_export_v1_01D314_7440C3_FC79F2`
GROUP BY 1, 2;
```
* Once we have a successfully created materialized view, we can leverage it to easily query the costs a certain tenant made in a certain month using the `project_id` & `invoice_month` property. E.g. the following command would give us all costs of all tenants in the first half of 2021 formatted as JSON:
```
bq --project_id meshstack-root query --format json --nouse_legacy_sql \
SELECT * FROM `meshstack-root.billing_export.collie-billing-view` WHERE invoice_month > '202101' AND invoice_month < '202107'
```

**Comment by Jelledb** [comment]
GCP billing is now supported!

**Comment by davezen1** [comment]
How do we input the billing project name in the CLI?
