### ISSUE TITLE
Links in the generated documentation webpage are not working for windows OS

### ISSUE THREAD

**Issue by ishabakeh** [meshcloud/collie-cli#191]
**Describe the bug**
on windows based OS, when we generate the documentation, links to the kits on the left panel in the webpage are not working and reply 404.

**Reach of the bug**
All users of collie whom using windows based operating systems

**Impact of the bug**
They couldn't generate a proper documentation for their foundation.

**To Reproduce**
1- have some kit modules
2- do "collie foundation docs <name of the foundation> --preview"
3- in the generated webpage look for the links on the left pane which points to the kit modules or platform

**Expected behavior**
it should redirect us to the information about the respective module

**Screenshots**
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/96071919/205329335-5763dfb2-ba02-48a5-b6cd-a4d45136f783.png">

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/96071919/205330750-24abc561-b377-45c4-b490-aa02fe86dedc.png">

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/96071919/205331887-8cc86ad2-d7c5-42b4-8bd0-304f0a07a894.png">

**Desktop (please complete the following information):**
 - OS: windows
 - Version: 10,11,server 2019

**Comment by j0g3sc** [comment]
Fixed with https://github.com/meshcloud/collie-cli/pull/192.
I will create a new collie release later today.
