### ISSUE TITLE
deploying a platform with a single module fails

### ISSUE THREAD

**Issue by felixzieger** [meshcloud/collie-cli#196]
**Describe the bug**
Running collie foundation deploy for a foundation with one platform and only one applied kit module in that platform leads to collie expecting a terragrunt.hcl in the platform folder.

Example output for a foudnation (zero2lz) with a single platform (aws) and a single module in there (meshplatform) :
```
collie foundation deploy zero2lz
running 'apply' in foundations/zero2lz ...
running 'apply' in foundations/zero2lz/platforms/aws ...
detected a single platform module at foundations/zero2lz/platforms/aws, will deploy with "terragrunt <cmd>"
ERRO[0000] Error reading file at path /Users/fzieger/meshcloud/zero2lz-cloudfoundation/foundations/zero2lz/platforms/aws/terragrunt.hcl: open /Users/fzieger/meshcloud/zero2lz-cloudfoundation/foundations/zero2lz/platforms/aws/terragrunt.hcl: no such file or directory
```

**Reach of the bug**
Users that do not have a bootstrap module only. So most should be fine.

**Impact of the bug**
Collie does not apply the module

**To Reproduce**
Create a foundation with one platform. 
Create a kit module.
Apply this kit module to the platform.
Run collie foundation deploy for the foundation.

**Expected behavior**
collie applies the module.

**Implementation Hints**
The PlatformDeployer.ts needs to be adapted to figure out how to deploy the module.
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/67903933/224089633-5611df98-6128-4e67-93bf-92c5c76d746c.png">

**Comment by JohannesRudolph** [comment]
Closed as the PR fixing this has been merged already.
