### ISSUE TITLE
Support Custom platforms

### ISSUE THREAD

**Issue by malhussan** [meshcloud/collie-cli#292]
When creating a new foundation with collie; i.e. `collie foundation new`, I can currently add one of aws, azure or gcp as a platform.
<img width="670" alt="image" src="https://github.com/user-attachments/assets/ae804270-7be1-4438-a5b0-68d595102be6">

I want to have another option, "custom", to be able to add any platform in a foundation.

As a first version, the generated README.md would simply contain

```
---
id: <id>
name: <name>
type: <my-custom-platform>
---

# <name>
  
This is a custom platform.
```

**Comment by JohannesRudolph** [comment]
closed via #293
