### ISSUE TITLE
Error detection doesn't show missing rights; says you're not logged in instead

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#35]
The following happened when trying to collect IAM information across GCP tenants when missing a right for one of the tenants: 
```
ERROR: (gcloud.projects.get-ancestors-iam-policy) User is not permitted to access IAM policy for one or more of the ancestors
```
Instead, Collie CLI tells me:
```
INFO You are not logged in into GCP CLI. Please disconnect GCP with "Collie config --disconnect GCP or login into GCP CLI."
```

This is wrong information and we should check more explicitly if it's really a "not logged in" situation.

Implementation hint:
When receiving result code `1` from `gcloud`, we have to detect if it's really a "not logged in" error. If not, we should throw something like `"An unknown error occurred for tenant XYZ: " + result.stderr` so it's clearly visible what went wrong. As a bonus, it would also be great to know for which tenant this issue occurred (GCP does not include this information in the response)

**Comment by tfelix** [comment]
But if I understood this correctly this is currently hard to fix as the error happens in your IAM branch? I could look into it after the merge.
