### ISSUE TITLE
Loading indicator not working for Ubuntu

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#37]
![image](https://user-images.githubusercontent.com/14248574/124276748-7d37cc80-db44-11eb-8995-f554d5908061.png)

I saw it happening live too; the clearing of text in the terminal doesn't work at all.

**Comment by tfelix** [comment]
hm thats bad... because here it works... :/ 
![image](https://user-images.githubusercontent.com/1186998/124299193-710c3900-db5d-11eb-894b-b9ef779197b1.png)
Mabe it has something to do with the compiled version?

**Comment by Jelledb** [comment]
@tfelix are you using bash or zsh? Pubudu noticed it might be the combination of Ubuntu + zsh
Maybe you could try it out what happens when using zsh?

**Comment by tfelix** [comment]
I am using zsh. But I might test it via Bash and/or sh

**Comment by tfelix** [comment]
I observed breakage of the loading indicator, especially if the text overflows. Maybe this is the issue that the text went at the screen border? But I thought I tried to limit the characters. I think 42 chars is somewhat safe to assume for a modern terminal.
