### ISSUE TITLE
Support `collie tenant iam` for AWS

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#41]
We currently do not support AWS for retrieving IAM information. This has the following two reasons:

* It is unclear how exactly you can properly execute commands across multiple AWS Accounts. 
* It is unclear how exactly the role model within AWS should look like and if it integrates well with the shared model that is currently used by Azure & GCP (which is pretty much identical)

**Comment by tfelix** [comment]
We could configure a role (defaulting to AWS `OrganizationAccountAccessRole`) which collie tries to assume when accessing an AWS account.

**Comment by Jelledb** [comment]
Tip from Johannes -> https://github.com/alestic/aws-cli-multi-account-sessions
This project could act as inspiration for this implementation

**Comment by DorukAkinci** [comment]
I want to clarify this a little bit more. Yes this is actually perfectly possible scenario and this tool absolutely needs this as a feature however there are a few important points:

1- If you create an AWS account from AWS Organization panel. This creates `OrganizationAccountAccessRole` as a default behaviour and it has `AdministratorAccess on it`
2- Our meshcloud way changes this behaviour. We don't use the account name parameter as Default and we set it as `MeshstackAccountAccessRole` and afterwards our replicator downgrades the Role's permission at the end to make it more secure.
3- So if a meshcloud customer wants this access role for theirselves, they should create `OrganizationAccountAccessRole` with our StackSets feature in the LandingZone configuration.
4- Maybe Collie-Cli can set different RoleNames per Account that it wants to assume or you can say we need one RoleName which is consistent for all of your accounts and jump on them from the management account.

**Comment by tfelix** [comment]
this is now implemented.
