### ISSUE TITLE
Inform users about new Collie releases

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#5]
To make users aware that a new Collie release is available with e.g. an important bug fix or a new exciting feature, we need some kind of system that can notify those users.

Implementation Hint:
It seems that Cliffy has some kind of support for upgrading CLIs: https://cliffy.io/command/#%E2%9D%AF-upgrade-command

**Comment by tfelix** [comment]
I did not fully understand how this works but it seems it works like checking out the repository and pushing that files then into deno runtime. This will fail on normal installations as this probably wont download the binary.

However we could implement a check for new releases which periodically queries github and if a new release is there informs the user to install it.

**Comment by JohannesRudolph** [comment]
We now have support for `collie upgrade` command and users can list available version with `collie upgrade -l` (when installed via deno install). 

I'd consider that good enough for now, as the alternative is that collie needs to check for new versions with a network call. That has user consent issues wrt. telemetry etc. so for now I'd consider having an explicit command that users call good enough. 

Sidenote: a tool that does proactive version checks and prominently features it in command output is `pip` (python package manager)
