### ISSUE TITLE
Add Info on tags for cloud costs to Options section

### ISSUE THREAD

**Issue by meshchristina** [meshcloud/collie-cli#60]
When analyzing my cloud costs, I would like to know which tags are used in order to map costs to corresponding cost centers etc. It's great that this is possible with Collie, but the functionality is a bit hidden. 

My proposal would be to add this info to the Options section of the collie tenant costs command, where it says "Defines the output format." Just add: "Use csv/json/yaml to view tags.

**Comment by Jelledb** [comment]
Solved it a bit differently. Instead, we always show tags.
