### ISSUE TITLE
collie [command] --help invocations are slow

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/collie-cli#65]
I've just setup collie cli on a new machine and was surprised by the time it takes to run a simple `collie --help` or `collie tenant --help`. I have all three cloud provider CLIs installed on my machine, and running the `--help` commands is something I do quite often when working with a new tool.

Here's some output from my machine. 

```
time collie --help
...
real	0m3.965s
user	0m2.099s
sys	0m0.629s


time collie tenant --help
...
real	0m2.732s
user	0m1.725s
sys	0m0.440s

```

While it's running my terminal (macOS standard terminal) shows me that it's running python 3.7, so I think there's some auto-detection of provider CLI going on, even though I have a valid collie config already.  Interestingly also `collie --version` is "slow". 

```
18:30 $ collie config list
┌───────┬──────┬───────┐
│ AWS   │ GCP  │ Azure │
├───────┼──────┼───────┤
│ false │ true │ true  │
└───────┴──────┴───────┘
1 entry. 
✔ ~ 
18:30 $ time collie --version
0.3.0
real	0m2.710s
user	0m1.724s
sys	0m0.429s

**Comment by tfelix** [comment]
Yes the provider availability is re-checked on every run. We can separate this though and only issue them when actually executing cloud related sub commands. See the opened PR.
