### ISSUE TITLE
Consistently use plural/singular for commands 

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/collie-cli#75]
It's a minor nitpick but I just tried to run `collie tenant cost` and had to learn that it's `collie tenant cost`**s** instead. 

So we have 

- collie tenant (singular)
- collie tenant list (singular)
- collie tenant iam (singular)
- collie tenant costs (plural)
- collie tenant analyze-tags (plural)

I don't have a strong preference and am not sure this needs to be harmonized at all, just wanted to point out this happened. Other tools for example do it like this

```
  # List all pods in ps output format.
  kubectl get pods
  
  # List all pods in ps output format with more information (such as node name).
  kubectl get pods -o wide
  
  # List a single replication controller with specified NAME in ps output format.
  kubectl get replicationcontroller web
```

**Comment by tfelix** [comment]
As discussed in the PR request, there will be a general overhaul of the command structure anyways as we are in need of unifying the syntax of cost and listing of tenants as this separation is confusing in general.

**Comment by tfelix** [comment]
Closed in favor of https://github.com/meshcloud/collie-cli/issues/96
